server:
  port: 9500

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能,,利用微服务名进行路由
      routes:
        - id: payment_routh1 #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://springcloud-payment-provider-service
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://springcloud-payment-provider-service
          predicates:
            - Path=/payment/getInfo/** #断言，路径相匹配的进行路由
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@pathKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
  redis:
    host: localhost
    port: 6379
    database: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,
        http://eureka7002.com:7002/eureka,
        http://eureka7003.com:7003/eureka
  instance:
    prefer-ip-address: true # 使用ip地址注册