server:
  port: 80
spring:
  application:
    name: springcloud-consumer-order-service
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        probability: 1.0
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置true才能配合ribbon	  使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,
                   http://eureka7002.com:7002/eureka,
                   http://eureka7003.com:7003/eureka
  instance:
    prefer-ip-address: true # 使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}