server:
  port: 80

spring:
  application:
    name: springcloud-consumer-consul-order
  ###consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name} # 服务名称
        register: true  # 是否需要注册
        instance-id: ${spring.application.name}_${server.port} # 实例的id
        prefer-ip-address: true # 开启ip地址注册